[package]
name = "v6"
version = "0.1.0"
authors = ["Rob Tamlyn <MemoryChips@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "sandbox"
path = "examples/sandbox/main.rs"
